services:
  availability: http://dummy.example.org/api/availability
  performance: http://dummy.example.org/api/performance
  health: http://dummy.example.org/api/health
  cis: http://dummy.example.org/api/cis
  capacity: http://dummy.example.org/api/capacity
  optimization: http://dummy.example.org/api/optimization
  security: http://dummy.example.org/api/security
  infra:
    foo_region:
      - id: horizon
        title: Horizon
        description: Web UI that manages OpenStack resources
        urls:
          -
            - http://nan

      - id: baremetal
        title: Baremetal Provisioning
        description: MaaS service that manages baremetal infrastructure
        urls:
          -
            - http://nan

      - id: jenkins
        title: Jenkins CI/CD
        description: Cloud Continues Integration and Deployment.
        urls:
          -
            - http://nan

      - id: git
        title: Git Source Control
        description: Gitlab with Git repositories with all projects source code
        urls:
          -
            - http://nan

      - id: packages
        title: JFrog Artifactory Packages
        description: JFrog Artifactory service that contains all cloud packages & images
        urls:
          -
            - http://nan

      - id: stacklight
        title: Stacklight
        description: Cloud Logging Metering and Alerting services
        urls:
          -
            - http://nan
